server:
    port: 8761

spring:
    application:
        name: EurekaServerApp

eurekaclient.register-with-eureka: false
eureka.client.fetch-registry: false

management.security.enabled: false
#logging.level.com.netflix.eureka=OFF
#logging.level.com.netflix.discovery=OFF