server:
    port: 8080

spring:
    application:
        name: EurekaClientApplication1

eurekaclient.register-with-eureka: true
eureka.client.fetch-registry: true

eureka.client.serviceUrl.defaultZone: http://localhost:8761/eureka/

management.security.enabled: false
#logging.level.com.netflix.eureka=OFF
#logging.level.com.netflix.discovery=OFF